apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "app.labels" . | indent 4 }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
